version: '3.6'
services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    entrypoint: /mssql/entrypoint.sh
    command: /opt/mssql/bin/sqlservr
    environment:
      SA_PASSWORD: "Your_password123!"
      ACCEPT_EULA: "Y"
    volumes:
      - ./mssql:/mssql
    ports:
      - "15785:1433"
  presto:
    image: "prestosql/presto"
    ports:
      - "8080:8080"
    volumes:
      - ./presto/etc:/usr/lib/presto/etc/
    depends_on:
      - mssql
  app:
    build: .
    volumes:
      - .:/home/app/notebook
      # Ensure we override any local pyenv configuration
      - ./.python-version-docker:/home/app/notebook/.python-version
    depends_on:
      - mssql
      - presto
